apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  namespace: spark
spec:
  serviceName: spark-master-headless
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-master
        image: custom-spark:3.4.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
          name: master-port
        - containerPort: 8080
          name: webui
        env:
        - name: SPARK_DAEMON_MEMORY
          value: "800m"
        resources:
          requests:
            cpu: 200m
            memory: 600Mi
          limits:
            cpu: 300m
            memory: 800Mi
        command:
        - /bin/bash
        - -c
        - |
          /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master \
            --host $(hostname -i) \
            --port 7077 \
            --webui-port 8080
        volumeMounts:
        - name: spark-events
          mountPath: /var/spark-events
        - name: spark-master-config
          mountPath: /opt/spark/conf/spark-defaults.conf
          subPath: spark-defaults.conf
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pgrep -f 'org.apache.spark.deploy.master.Master'
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 7077
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: spark-master-config
        configMap:
          name: spark-master-config
  volumeClaimTemplates:
  - metadata:
      name: spark-events
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-headless
  namespace: spark
spec:
  clusterIP: None
  selector:
    app: spark-master
  ports:
  - name: master-port
    port: 7077
    targetPort: 7077
  - name: webui
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: spark
spec:
  selector:
    app: spark-master
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
